### PR TITLE
proxy /ws requests to linked backend component

### PR DESCRIPTION
**Pull request by ryanj**
ready for testing and review @gshipley @jorgemoralespou

### CODE REVIEW

**Comment by ryanj** [comment]
The `odo link` code seems to work, but I'm seeing this error when I try to push to Online Pro:
```bash
$ odo push
Pushing changes to component: gamefrontend
my localpath is /home/ryanj/src/Wild-West-Frontend
Please wait, building component....
chmod: changing permissions of '/tmp/src/.': Operation not permitted
failed to push component: gamefrontend
```

There is also an error in the event log about mismanaged PVs failing to attach, not sure if that is related

**Comment by jorgemoralespou** [comment]
@ryanj in online we might run into trouble with odo as it will configure deployments as rolling and that with a PVC attached might not work.

**Comment by ryanj** [comment]
## Testing instructions:

Environment: minishift v3.10.0

### Functional build and deploy test:

1. oc login
2. odo project myproject
3. odo app create demo
4. cd Wild-West-Frontend
5. odo create nodejs frontend
6. odo push
7. odo create url
8. xdg-open $(odo url list | tail -n 1 | cut -f 3 -d' ')

Expected Result: WildWestFrontend in your default browser

### Proxy testing (unconfigured error result):

1. curl $(odo url list | tail -n 1 | cut -f 3 -d' ')/ws/getRandomObject

Expected Result: "Error: service backend not configured"

### Proxy testing (success):

1. cd ../backend
2. mvn package
3. odo create wildfly backend --binary target/ROOT.war 
4. odo push
5. odo component frontend
6. odo link backend
7. xdg-open $(odo url list | tail -n 1 | cut -f 3 -d' ')/ws/getRandomObject

Expected Result: "Random Object"

**Comment by jorgemoralespou** [comment]
@ryanj this testing is wrong. You should deploy first the backend, then the frontend, with the frontend as active component, you should do `odo link backend`, then after the frontend pod is redeployed you should see the game, and not before.

**Comment by ryanj** [comment]
@GrahamDumpleton @gshipley @jorgemoralespou Ready to merge

**Pull request merged**
